import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  showRecipe: { flex: 1, backgroundColor: "#fff" },
  headerImage: { height: 200, alignItems: "center" },
  headerGradient: { resizeMode: "cover", height: 200, width: 500 },
  recipeImageContainer: {
    height: 200,
    width: 200,
    top: -100,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.48,
    shadowRadius: 11.95,
    elevation: 5,
    borderRadius: 22,
  },
  recipeImage: { height: 200, width: 200, borderRadius: 22 },
  infoContainer: { top: 120, flex: 1 },
  detailsView: { flexDirection: "column" },
  recipeLabel: {
    textAlign: "center",
    fontSize: 22,
    fontWeight: "bold",
    color: "#795548",
  },
  recipeSource: {
    textAlign: "center",
    fontSize: 12,
    color: "#795548",
  },
  recipeQuickDetailsView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  quickDetailsChips: {
    textAlign: "center",
    fontSize: 11,
    color: "#795548",
    marginRight: 10,
    backgroundColor: "#eeeeee",
    color: "#9e9e9e",
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 22,
  },
  RecipeInfoContainer: {
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
  },
  tabBar: {
    flexDirection: "row",
  },
  sectionTitleActive: {
    padding: 10,
    fontSize: 15,
    color: "#bf360c",
    fontWeight: "bold",
    borderBottomWidth: 2,
    borderBottomColor: "#bf360c",
    backgroundColor: "#fbe9e7",
  },
  sectionTitle: {
    fontSize: 15,
    color: "#ccc",
    padding: 10,
    backgroundColor: "#fafafa",
    borderBottomWidth: 2,
    borderBottomColor: "#e0e0e0",
  },
  ingredientsScroll: {
    padding: 15,
    marginBottom: 250,
    backgroundColor: "#fafafa",
  },
  ingredient: {
    color: "#9e9e9e",
    marginBottom: 10,
    paddingBottom: 10,
  },
  preparationDetails: {
    color: "#9e9e9e",
    marginBottom: 20,
  },
  healthLabelsContainer: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
  },
  healthLabel: {
    fontSize: 10,
    marginRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: "#ffe0b2",
    color: "#5d4037",
    borderRadius: 22,
    margin: 5,
  },
  dietLabel: {
    fontSize: 10,
    marginRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: "#c8e6c9",
    color: "#1b5e20",
    borderRadius: 22,
    margin: 5,
  },
  cautionLabel: {
    fontSize: 10,
    marginRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: "#ffcdd2",
    color: "#b71c1c",
    borderRadius: 22,
    margin: 5,
  },
  nutritionDetails: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 30,
  },
  nutrientsLabel: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: '#eeeeee',
    padding: 5,
    paddingLeft: 8,
    paddingRight: 8,
    margin: 5,
    borderRadius: 5,
  },
  nutrientLabel:{
    fontSize: 10,
    color: '#bdbdbd',
  },
  nutrientValue:{
    fontSize: 15,
    color: '#616161',
  }
});
